### ISSUE TITLE
Problem z interpreterem

### ISSUE THREAD

**Issue by annag7** [gniadekk/Gra-#2]
Pycharm nie znajduje mi interpretera. W jakim folderze powinien być? Bo może źle wybieram

**Comment by gniadekk** [comment]
Aby skonfigurować interpreter w programie PyCharm możesz wykorzystać inną instalacje Pythona, proponuję Anaconde. Jest wiele innych interpreterów, lecz ten sposób uważam za najprostszy. Link do programu jak i tuturial scomitowałem na gita.
